version: "3.8"
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
      # target: dev
    volumes:
      - ./bot:/usr/src/bot
    networks:
      - data-db-network
      - storage-network
    env_file:
      - env/.env
      - env/.env.dev
      - env/.env.prod
      - env/.env.local
    depends_on:
      - db
      - check-db-started
      - storage

  db:
    image: postgres:15.1-alpine
    volumes:
      - ./database/postgresql/data:/var/lib/postgresql/data
    networks:
      - data-db-network
    env_file:
      - env/.env
      - env/.env.dev
      - env/.env.prod
      - env/.env.local
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
  # Wait for Database
  check-db-started: 
    image: jwilder/dockerize:0.6.1
    depends_on:
      - db
    command: dockerize -wait=tcp://$${POSTGRES_SERVER}/$${POSTGRES_DB}

  migrator:
    build:
      context: ./migrator
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./migrator:/usr/src/migrator
    networks:
      - data-db-network
    env_file:
      - env/.env
      - env/.env.dev
      - env/.env.prod
      - env/.env.local
    depends_on:
      - db

  storage:
    build:
      context: ./redis
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./redis/redis-data:/var/lib/redis
#      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - storage-network
    environment:
      - REDIS_REPLICATION_MODE=master
    env_file:
      - env/.env
      - env/.env.dev
      - env/.env.prod
      - env/.env.local

networks:
  data-db-network:
    driver: bridge
  storage-network:
    driver: bridge
