version: "3.8"
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
      # target: dev
    networks:
      - data-db-network
    env_file:
      - env/.env
      - env/.env.dev
      - env/.env.local
    volumes:
      - ./bot:/usr/src/bot
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    volumes:
      - ./database/postgresql/data:/var/lib/postgresql/data
    networks:
      - data-db-network
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
    env_file:
      - env/.env
      - env/.env.dev
      - env/.env.local

networks:
    data-db-network:
        driver: bridge
