version: "3.9"
services:
  bot:
    build:
      target: prod
    restart: always
    env_file:
      - env/.env
      - env/.env.prod
      - env/.env.local

  db:
    env_file:
      - env/.env
      - env/.env.prod
      - env/.env.local

  migrator:
    build:
      target: prod
    env_file:
      - env/.env
      - env/.env.prod
      - env/.env.local

  storage:
    env_file:
      - env/.env
      - env/.env.prod
      - env/.env.local


